### ISSUE TITLE
Does not display correctly on the iPhone

### ISSUE THREAD

**Issue by josephroberts** [BlackrockDigital/startbootstrap-freelancer#38]
Hi,

I have made a website using the template, adapting it to my needs. It works great however on the iPhone the menu bar at the top covers the portfolio image. Any idea how to fix this?

The problem can be seen at www.joseph-roberts.co.uk 

It also shows up when using device mode in chrome with an iPhone selected.

Thanks
Joe

**Comment by bencomeau** [comment]
I know this is rather old but figured you might still be in need of the solution. Looking at your freelancer.css file I see the line 88 is missing the padding declarations.

```css
header .container {
    padding-top: 0px;
    padding-bottom: 0px;
}
```

Needs to be 

```css
header .container {
    padding-top: 100px;
    padding-bottom: 50px;
}
```

Using Responsive View Design I can see this fixes the issue.

![paddingtop](https://cloud.githubusercontent.com/assets/10427571/9620719/ed72b0c6-50d2-11e5-8233-b45a46b6f2b0.png)
